// CRA rule selections retain their original severities during the flat-config migration.
// Rule selections adapted from eslint-config-react-app (MIT), Copyright (c) Facebook, Inc.
import js from '@eslint/js';
import vitest from '@vitest/eslint-plugin';
import restrictedGlobals from 'confusing-browser-globals';
import imports from 'eslint-plugin-import';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import testingLibrary from 'eslint-plugin-testing-library';
import globals from 'globals';
import { defineConfig } from 'eslint/config';

export default defineConfig([
  { ignores: ['build/**', 'coverage/**', 'node_modules/**'] },
  {
    files: ['**/*.{js,jsx}'],
    ...js.configs.recommended,
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: { ecmaFeatures: { jsx: true } },
      globals: { ...globals.browser, ...globals.node },
    },
    plugins: {
      import: imports,
      'jsx-a11y': jsxA11y,
      react,
      'react-hooks': { rules: reactHooks.rules },
    },
    settings: { react: { version: 'detect' } },
    rules: {
      ...js.configs.recommended.rules,
      'no-restricted-globals': ['error', ...restrictedGlobals],
      "react/jsx-uses-vars": "warn",
      "react/jsx-uses-react": "warn",
      "array-callback-return": "warn",
      "default-case": ["warn",{"commentPattern":"^no default$"}],
      "dot-location": ["warn","property"],
      "eqeqeq": ["warn","smart"],
      "new-parens": "warn",
      "no-array-constructor": "warn",
      "no-caller": "warn",
      "no-cond-assign": ["warn","except-parens"],
      "no-const-assign": "warn",
      "no-control-regex": "warn",
      "no-delete-var": "warn",
      "no-dupe-args": "warn",
      "no-dupe-class-members": "warn",
      "no-dupe-keys": "warn",
      "no-duplicate-case": "warn",
      "no-empty-character-class": "warn",
      "no-empty-pattern": "warn",
      "no-eval": "warn",
      "no-ex-assign": "warn",
      "no-extend-native": "warn",
      "no-extra-bind": "warn",
      "no-extra-label": "warn",
      "no-fallthrough": "warn",
      "no-func-assign": "warn",
      "no-implied-eval": "warn",
      "no-invalid-regexp": "warn",
      "no-iterator": "warn",
      "no-label-var": "warn",
      "no-labels": ["warn",{"allowLoop":true,"allowSwitch":false}],
      "no-lone-blocks": "warn",
      "no-loop-func": "warn",
      "no-mixed-operators": ["warn",{"groups":[["&","|","^","~","<<",">>",">>>"],["==","!=","===","!==",">",">=","<","<="],["&&","||"],["in","instanceof"]],"allowSamePrecedence":false}],
      "no-multi-str": "warn",
      "no-global-assign": "warn",
      "no-unsafe-negation": "warn",
      "no-new-func": "warn",
      "no-new-object": "warn",
      "no-new-symbol": "warn",
      "no-new-wrappers": "warn",
      "no-obj-calls": "warn",
      "no-octal": "warn",
      "no-octal-escape": "warn",
      "no-redeclare": "warn",
      "no-regex-spaces": "warn",
      "no-restricted-syntax": ["warn","WithStatement"],
      "no-script-url": "warn",
      "no-self-assign": "warn",
      "no-self-compare": "warn",
      "no-sequences": "warn",
      "no-shadow-restricted-names": "warn",
      "no-sparse-arrays": "warn",
      "no-template-curly-in-string": "warn",
      "no-this-before-super": "warn",
      "no-throw-literal": "warn",
      "no-undef": "error",
      "no-unreachable": "warn",
      "no-unused-expressions": ["error",{"allowShortCircuit":true,"allowTernary":true,"allowTaggedTemplates":true}],
      "no-unused-labels": "warn",
      "no-unused-vars": ["warn",{"args":"none","ignoreRestSiblings":true}],
      "no-use-before-define": ["warn",{"functions":false,"classes":false,"variables":false}],
      "no-useless-computed-key": "warn",
      "no-useless-concat": "warn",
      "no-useless-constructor": "warn",
      "no-useless-escape": "warn",
      "no-useless-rename": ["warn",{"ignoreDestructuring":false,"ignoreImport":false,"ignoreExport":false}],
      "no-with": "warn",
      "no-whitespace-before-property": "warn",
      "react-hooks/exhaustive-deps": "warn",
      "require-yield": "warn",
      "rest-spread-spacing": ["warn","never"],
      "strict": ["warn","never"],
      "unicode-bom": ["warn","never"],
      "use-isnan": "warn",
      "valid-typeof": "warn",
      "no-restricted-properties": ["error",{"object":"require","property":"ensure","message":"Please use import() instead. More info: https://facebook.github.io/create-react-app/docs/code-splitting"},{"object":"System","property":"import","message":"Please use import() instead. More info: https://facebook.github.io/create-react-app/docs/code-splitting"}],
      "getter-return": "warn",
      "import/first": "error",
      "import/no-amd": "error",
      "import/no-anonymous-default-export": "warn",
      "import/no-webpack-loader-syntax": "error",
      "react/forbid-foreign-prop-types": ["warn",{"allowInPropTypes":true}],
      "react/jsx-no-comment-textnodes": "warn",
      "react/jsx-no-duplicate-props": "warn",
      "react/jsx-no-target-blank": "warn",
      "react/jsx-no-undef": "error",
      "react/jsx-pascal-case": ["warn",{"allowAllCaps":true,"ignore":[]}],
      "react/no-danger-with-children": "warn",
      "react/no-direct-mutation-state": "warn",
      "react/no-is-mounted": "warn",
      "react/no-typos": "error",
      "react/require-render-return": "error",
      "react/style-prop-object": "warn",
      "jsx-a11y/alt-text": "warn",
      "jsx-a11y/anchor-has-content": "warn",
      "jsx-a11y/anchor-is-valid": ["warn",{"aspects":["noHref","invalidHref"]}],
      "jsx-a11y/aria-activedescendant-has-tabindex": "warn",
      "jsx-a11y/aria-props": "warn",
      "jsx-a11y/aria-proptypes": "warn",
      "jsx-a11y/aria-role": ["warn",{"ignoreNonDOM":true}],
      "jsx-a11y/aria-unsupported-elements": "warn",
      "jsx-a11y/heading-has-content": "warn",
      "jsx-a11y/iframe-has-title": "warn",
      "jsx-a11y/img-redundant-alt": "warn",
      "jsx-a11y/no-access-key": "warn",
      "jsx-a11y/no-distracting-elements": "warn",
      "jsx-a11y/no-redundant-roles": "warn",
      "jsx-a11y/role-has-required-aria-props": "warn",
      "jsx-a11y/role-supports-aria-props": "warn",
      "jsx-a11y/scope": "warn",
      "react-hooks/rules-of-hooks": "error",
    },
  },
  {
    files: ['src/**/*.{test,spec}.{js,jsx}', 'src/setupTests.js'],
    plugins: { vitest, 'testing-library': testingLibrary },
    languageOptions: { globals: vitest.environments.env.globals },
    rules: {
      ...vitest.configs.recommended.rules,
      "vitest/no-conditional-expect": "error",
      "vitest/no-identical-title": "error",
      "vitest/no-interpolation-in-snapshots": "error",
      "vitest/no-mocks-import": "error",
      "vitest/valid-describe-callback": "error",
      "vitest/valid-expect": "error",
      "vitest/valid-expect-in-promise": "error",
      "vitest/valid-title": "warn",
      "testing-library/await-async-queries": "error",
      "testing-library/await-async-utils": "error",
      "testing-library/no-await-sync-queries": "error",
      "testing-library/no-container": "error",
      "testing-library/no-debugging-utils": "error",
      "testing-library/no-dom-import": ["error","react"],
      "testing-library/no-node-access": "error",
      "testing-library/no-promise-in-fire-event": "error",
      "testing-library/no-render-in-lifecycle": "error",
      "testing-library/no-unnecessary-act": "error",
      // Testing Library 6 removed the empty-callback rule; retain the check here.
      'no-restricted-syntax': [
        'error',
        'WithStatement',
        {
          selector: 'CallExpression:matches([callee.name="waitFor"], [callee.property.name="waitFor"]) > :matches(ArrowFunctionExpression, FunctionExpression)[body.type="BlockStatement"][body.body.length=0]',
          message: 'Avoid waitFor with an empty callback.',
        },
      ],
      "testing-library/no-wait-for-multiple-assertions": "error",
      "testing-library/no-wait-for-side-effects": "error",
      "testing-library/no-wait-for-snapshot": "error",
      "testing-library/prefer-find-by": "error",
      "testing-library/prefer-presence-queries": "error",
      "testing-library/prefer-query-by-disappearance": "error",
      "testing-library/prefer-screen-queries": "error",
      "testing-library/render-result-naming-convention": "error",
    },
  },
]);
